### ISSUE TITLE
Genshin-DB api error

### ISSUE THREAD

**Issue by Nigh** [Genshin-bots/ImageGenerateServer#1]
## Input

`https://api.minigg.cn/characters?resultLanguage=CHS&query=%E4%B8%80&stats=90`

## Output

```
TypeError: genshindb.characters(...).stats is not a function
    at /www/supervisor/Genshin-DB/express.js:72:59
    at Layer.handle [as handle_request] (/www/supervisor/Genshin-DB/node_modules/express/lib/router/layer.js:95:5)
    at next (/www/supervisor/Genshin-DB/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/www/supervisor/Genshin-DB/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/www/supervisor/Genshin-DB/node_modules/express/lib/router/layer.js:95:5)
    at /www/supervisor/Genshin-DB/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/www/supervisor/Genshin-DB/node_modules/express/lib/router/index.js:341:12)
    at next (/www/supervisor/Genshin-DB/node_modules/express/lib/router/index.js:275:10)
    at next (/www/supervisor/Genshin-DB/node_modules/express/lib/router/route.js:127:14)
    at next (/www/supervisor/Genshin-DB/node_modules/express/lib/router/route.js:131:14)
```

**Comment by Nigh** [comment]
并且，似乎数据库很久未更新了。稍新的角色都是`"specialized":0.2420000024139881`

是否还在维护呢？

**Comment by MiniGrayGay** [comment]
滴滴，在维护的啊

**Comment by MiniGrayGay** [comment]
查询的“一”由于匹配到的不是单个角色名字，有多个角色符合关键字“一”：["迪奥娜","罗莎莉亚","托马"]，所以不能查询具体消耗

**Comment by MiniGrayGay** [comment]
"specialized":0.2420000024139881 这个是由于最近暴击率的角色多，24.2%就是0.242嘛，例如云堇是126.7%元素充能，角色基础是100%，所以"specialized":0.26669999957084656，就是26.7%，申鹤攻击力28.8%是"specialized":0.2879999876022339

**Comment by Nigh** [comment]
意思是，可以返回个错误码啥的。直接返回了报错信息，不好处理。

还好在维护，因为没找到其他支持中文的接口，差点准备自己搭了。

**Comment by Nigh** [comment]
`https://api.minigg.cn/characters?resultLanguage=CHS&query=%E9%A6%99%E8%8F%B1&stats=90`
返回就是
`{"level":90,"ascension":6,"hp":10874.91499475576,"attack":225.14102222725342,"defense":668.8711049900703,"specialized":96}`
貌似`specialized`这个字段不统一？

**Comment by MiniGrayGay** [comment]
参照米游社 香菱的信息，元素精通是整数96，所以api返回是96，像攻击百分比，暴击率百分比，24.2%转换成小数表示就是0.242了

**Comment by Nigh** [comment]
> 参照米游社 香菱的信息，元素精通是整数96，所以api返回是96，像攻击百分比，暴击率百分比，24.2%转换成小数表示就是0.242了

感谢回复。理解了。就是要先获取`substat`字段，拿到突破提升的属性，再结合`specialized`字段计算对吧。

**Comment by MiniGrayGay** [comment]
yes，IGS和Wiki接口的问题也可以来群929275476吹吹水
